# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: buf/validate/priv/private.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class FieldConstraints(betterproto.Message):
    """Do not use. Internal to protovalidate library"""

    cel: List["Constraint"] = betterproto.message_field(1)


@dataclass
class Constraint(betterproto.Message):
    """Do not use. Internal to protovalidate library"""

    id: str = betterproto.string_field(1)
    message: str = betterproto.string_field(2)
    expression: str = betterproto.string_field(3)
