# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: native/v1/native.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import List

import betterproto

from sdk.compass import v1


class AddVehicleStatus(betterproto.Enum):
    UNSPECIFIED = 0
    APPROVED = 1
    PENDING = 2
    FAILED = 3


class HistoricalExportFilterType(betterproto.Enum):
    """Type of information to be exported"""

    # Refers to raw data point returned from the vehicle
    POINT = 0
    # Refers to the road matched compass processed trip information
    TRIP = 1


@dataclass
class ToyotaAuth(betterproto.Message):
    # Refers to the vin of the toyota vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the toyota account that the vehicle has been
    # linked to
    username: str = betterproto.string_field(2)
    # Refers to the password of the toyota account that the vehicle has been
    # linked to
    password: str = betterproto.string_field(3)


@dataclass
class LexusAuth(betterproto.Message):
    # Refers to the vin of the toyota vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the toyota account that the vehicle has been
    # linked to
    username: str = betterproto.string_field(2)
    # Refers to the password of the toyota account that the vehicle has been
    # linked to
    password: str = betterproto.string_field(3)


@dataclass
class TeslaAuth(betterproto.Message):
    # Refers to the vin of the tesla vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class TeslaSignup(betterproto.Message):
    # Refers to the vin of the tesla vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    id: str = betterproto.string_field(2)


@dataclass
class HyundaiAuth(betterproto.Message):
    # Refers to the vin of the hyundai vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the hyundai account that the vehicle has been
    # linked to
    username: str = betterproto.string_field(2)
    # Refers to the password of the hyundai account that the vehicle has been
    # linked to
    password: str = betterproto.string_field(3)


@dataclass
class GenesisAuth(betterproto.Message):
    # Refers to the vin of the genesis vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the genesis account that the vehicle has been
    # linked to
    username: str = betterproto.string_field(2)
    # Refers to the password of the genesis account that the vehicle has been
    # linked to
    password: str = betterproto.string_field(3)


@dataclass
class KiaAuth(betterproto.Message):
    # Refers to the vin of the kia vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the kia account that the vehicle has been linked
    # to
    username: str = betterproto.string_field(2)
    # Refers to the password of the kia account that the vehicle has been linked
    # to
    password: str = betterproto.string_field(3)


@dataclass
class FordAuth(betterproto.Message):
    # Refers to the vin of the ford vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the ford account that the vehicle has been linked
    # to
    username: str = betterproto.string_field(2)
    # Refers to the password of the ford account that the vehicle has been linked
    # to
    password: str = betterproto.string_field(3)


@dataclass
class StellantisAuth(betterproto.Message):
    # Refers to the vin of the stellantis vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class AbarthAuth(betterproto.Message):
    # Refers to the vin of the Abarth vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class AlfaRomeoAuth(betterproto.Message):
    # Refers to the vin of the Alfa Romeo vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class ChryslerAuth(betterproto.Message):
    # Refers to the vin of the Chrysler vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class CitroenAuth(betterproto.Message):
    # Refers to the vin of the Citroën vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class DodgeAuth(betterproto.Message):
    # Refers to the vin of the Dodge vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class DSAutoAuth(betterproto.Message):
    # Refers to the vin of the DS Auto vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class FiatAuth(betterproto.Message):
    # Refers to the vin of the Fiat vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class JeepAuth(betterproto.Message):
    # Refers to the vin of the Jeep vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class OpelAuth(betterproto.Message):
    # Refers to the vin of the Opel vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class PeugeotAuth(betterproto.Message):
    # Refers to the vin of the Peugeot vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class RamAuth(betterproto.Message):
    # Refers to the vin of the Ram vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class VauxhallAuth(betterproto.Message):
    # Refers to the vin of the Vauxhall vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class MaseratiAuth(betterproto.Message):
    # Refers to the vin of the Maserati vehicle added to the fleet
    vin: str = betterproto.string_field(1)


@dataclass
class AuthRequest(betterproto.Message):
    # to be used for toyota vehicles
    toyota: "ToyotaAuth" = betterproto.message_field(1, group="provider")
    # to be used for tesla vehicles
    tesla: "TeslaAuth" = betterproto.message_field(2, group="provider")
    # to be used for lexus vehicles
    lexus: "LexusAuth" = betterproto.message_field(3, group="provider")
    # to be used for abarth vehicles
    abarth: "AbarthAuth" = betterproto.message_field(4, group="provider")
    # to be used for alpha_romeo vehicles
    alpha_romeo: "AlfaRomeoAuth" = betterproto.message_field(5, group="provider")
    # to be used for chrysler vehicles
    chrysler: "ChryslerAuth" = betterproto.message_field(6, group="provider")
    # to be used for citroen vehicles
    citroen: "CitroenAuth" = betterproto.message_field(7, group="provider")
    # to be used for dodge vehicles
    dodge: "DodgeAuth" = betterproto.message_field(8, group="provider")
    # to be used for ds_auto vehicles
    ds_auto: "DSAutoAuth" = betterproto.message_field(9, group="provider")
    # to be used for fiat vehicles
    fiat: "FiatAuth" = betterproto.message_field(10, group="provider")
    # to be used for jeep vehicles
    jeep: "JeepAuth" = betterproto.message_field(11, group="provider")
    # to be used for opel vehicles
    opel: "OpelAuth" = betterproto.message_field(12, group="provider")
    # to be used for peugeot vehicles
    peugeot: "PeugeotAuth" = betterproto.message_field(13, group="provider")
    # to be used for ram vehicles
    ram: "RamAuth" = betterproto.message_field(14, group="provider")
    # to be used for vauxhall vehicles
    vauxhall: "VauxhallAuth" = betterproto.message_field(15, group="provider")
    # to be used for maserati vehicles
    maserati: "MaseratiAuth" = betterproto.message_field(16, group="provider")
    # to be used for hyundai vehicles
    hyundai: "HyundaiAuth" = betterproto.message_field(17, group="provider")
    # to be used for genesis vehicles
    genesis: "GenesisAuth" = betterproto.message_field(18, group="provider")
    # to be used for ford vehicles
    ford: "FordAuth" = betterproto.message_field(19, group="provider")
    # to be used for kia vehicles
    kia: "KiaAuth" = betterproto.message_field(20, group="provider")


@dataclass
class SignupRequest(betterproto.Message):
    tesla: "TeslaSignup" = betterproto.message_field(2, group="provider")


@dataclass
class AddVehicleResponse(betterproto.Message):
    add_vehicle_status: "AddVehicleStatus" = betterproto.enum_field(1)
    message: str = betterproto.string_field(2)


@dataclass
class AuthResponse(betterproto.Message):
    payload: str = betterproto.string_field(1)
    expiry: datetime = betterproto.message_field(2)


@dataclass
class SetLockCommand(betterproto.Message):
    # Vehicle will be locked if set to true
    locked: bool = betterproto.bool_field(1)


@dataclass
class IssueActionRequest(betterproto.Message):
    vin: str = betterproto.string_field(1)
    lock: "SetLockCommand" = betterproto.message_field(2, group="command")


@dataclass
class GetLatestPointRequest(betterproto.Message):
    # vin of the vehicle for which the latest location is required
    vin: str = betterproto.string_field(1)


@dataclass
class GetLatestPointResponse(betterproto.Message):
    # contains all the data variants returned by each provider
    event: v1.PositionEvent = betterproto.message_field(1)


@dataclass
class HistoricalExportRequest(betterproto.Message):
    # list of vins of vehicles for which historical data export is required
    filter_vins: List[str] = betterproto.string_field(1)
    # Date range for the historical data export
    filter_dates: v1.DateTimeRange = betterproto.message_field(2)
    # Refers to the type of data export required (raw data points or road matched
    # and processed trips)
    filter_type: "HistoricalExportFilterType" = betterproto.enum_field(3)


@dataclass
class HistoricalExportResponse(betterproto.Message):
    # contains links to csv files which contain the output for the historical
    # export @default: ["aefad", "Tuesday"]
    csv_links: List[str] = betterproto.string_field(1)


@dataclass
class AddVehicleRequest(betterproto.Message):
    # contains vehicle credential details that need to be added to the fleet
    provider_auth: "AuthRequest" = betterproto.message_field(1)


@dataclass
class GetVehiclesResponse(betterproto.Message):
    # returns all the details of vehicles part of the current fleet
    provider_get: List["GetRequest"] = betterproto.message_field(1)


@dataclass
class UpdateVehicleRequest(betterproto.Message):
    # contains vehicle credential details that need to be updated in the fleet
    provider_auth: "AuthRequest" = betterproto.message_field(1)


@dataclass
class RemoveVehicleRequest(betterproto.Message):
    # list of vins of vehicles that need to be removed from the fleet
    vins: List[str] = betterproto.string_field(1)


@dataclass
class GetTripsRequest(betterproto.Message):
    vin: str = betterproto.string_field(1)


@dataclass
class GetTripsResponse(betterproto.Message):
    events: List[v1.PositionEvent] = betterproto.message_field(1)


@dataclass
class ToyotaGet(betterproto.Message):
    # Refers to the vin of the toyota vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the toyota account that the vehicle has been
    # linked to
    username: str = betterproto.string_field(2)


@dataclass
class LexusGet(betterproto.Message):
    # Refers to the vin of the toyota vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the toyota account that the vehicle has been
    # linked to
    username: str = betterproto.string_field(2)


@dataclass
class TeslaGet(betterproto.Message):
    # Refers to the vin of the tesla vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the tesla account that the vehicle has been
    # linked to
    username: str = betterproto.string_field(2)


@dataclass
class HyundaiGet(betterproto.Message):
    # Refers to the vin of the hyundai vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the hyundai account that the vehicle has been
    # linked to
    username: str = betterproto.string_field(2)


@dataclass
class GenesisGet(betterproto.Message):
    # Refers to the vin of the genesis vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the genesis account that the vehicle has been
    # linked to
    username: str = betterproto.string_field(2)


@dataclass
class FordGet(betterproto.Message):
    # Refers to the vin of the ford vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the ford account that the vehicle has been linked
    # to
    username: str = betterproto.string_field(2)


@dataclass
class KiaGet(betterproto.Message):
    # Refers to the vin of the kia vehicle added to the fleet
    vin: str = betterproto.string_field(1)
    # Refers to the username of the kia account that the vehicle has been linked
    # to
    username: str = betterproto.string_field(2)


@dataclass
class GetRequest(betterproto.Message):
    # to be used for toyota vehicles
    toyota: "ToyotaGet" = betterproto.message_field(1, group="provider")
    # to be used for tesla vehicles
    tesla: "TeslaGet" = betterproto.message_field(2, group="provider")
    # to be used for lexus vehicles
    lexus: "LexusGet" = betterproto.message_field(3, group="provider")
    # to be used for abarth vehicles
    abarth: "AbarthAuth" = betterproto.message_field(4, group="provider")
    # to be used for alpha_romeo vehicles
    alpha_romeo: "AlfaRomeoAuth" = betterproto.message_field(5, group="provider")
    # to be used for chrysler vehicles
    chrysler: "ChryslerAuth" = betterproto.message_field(6, group="provider")
    # to be used for citroen vehicles
    citroen: "CitroenAuth" = betterproto.message_field(7, group="provider")
    # to be used for dodge vehicles
    dodge: "DodgeAuth" = betterproto.message_field(8, group="provider")
    # to be used for ds_auto vehicles
    ds_auto: "DSAutoAuth" = betterproto.message_field(9, group="provider")
    # to be used for fiat vehicles
    fiat: "FiatAuth" = betterproto.message_field(10, group="provider")
    # to be used for jeep vehicles
    jeep: "JeepAuth" = betterproto.message_field(11, group="provider")
    # to be used for opel vehicles
    opel: "OpelAuth" = betterproto.message_field(12, group="provider")
    # to be used for peugeot vehicles
    peugeot: "PeugeotAuth" = betterproto.message_field(13, group="provider")
    # to be used for ram vehicles
    ram: "RamAuth" = betterproto.message_field(14, group="provider")
    # to be used for vauxhall vehicles
    vauxhall: "VauxhallAuth" = betterproto.message_field(15, group="provider")
    # to be used for maserati vehicles
    maserati: "MaseratiAuth" = betterproto.message_field(16, group="provider")
    # to be used for hyundai vehicles
    hyundai: "HyundaiGet" = betterproto.message_field(17, group="provider")
    # to be used for genesis vehicles
    genesis: "GenesisGet" = betterproto.message_field(18, group="provider")
    # to be used for ford vehicles
    ford: "FordGet" = betterproto.message_field(19, group="provider")
    # to be used for kia vehicles
    kia: "KiaGet" = betterproto.message_field(20, group="provider")
