# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: location/v1/location.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class ReverseGeocodeRequest(betterproto.Message):
    polygon_wkt: str = betterproto.string_field(1)


@dataclass
class ReverseGeocodeResponse(betterproto.Message):
    name: str = betterproto.string_field(1)
